### PR TITLE
chore: force install latest versions

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by avik-pal** [comment]
https://github.com/SciML/ModelingToolkitNeuralNets.jl/actions/runs/10753951674/job/29823981291?pr=39#step:6:823 @ChrisRackauckas needs a fix in Symbolics

**Comment by SebastianM-C** [comment]
I'll take a look, I assume I also need to do the `outputsize` update that you mentioned a while ago.

**Comment by SebastianM-C** [comment]
I can't seem to reproduce the error in CI, but instead I get
```julia-repl
julia> LuxCore.stateless_apply(chain, input.u, ca)
ERROR: MethodError: no method matching (::Dense{…})(::SymbolicUtils.BasicSymbolic{…}, ::@NamedTuple{…}, ::@NamedTuple{})
The object of type `Dense{typeof(tanh), Int64, Int64, Nothing, Nothing, Static.True}` exists, but no method is defined for this combination of argument types when trying to treat it as a callable object.

Closest candidates are:
  (::Dense)(::AbstractArray, ::Any, ::NamedTuple)
   @ Lux ~/.julia/dev/Lux/src/layers/basic.jl:340

Stacktrace:
  [1] apply(model::Dense{…}, x::SymbolicUtils.BasicSymbolic{…}, ps::@NamedTuple{…}, st::@NamedTuple{})
    @ LuxCore ~/.julia/dev/LuxCore/src/LuxCore.jl:155
  [2] macro expansion
    @ ~/.julia/dev/Lux/src/layers/containers.jl:0 [inlined]
  [3] applychain(layers::@NamedTuple{…}, x::SymbolicUtils.BasicSymbolic{…}, ps::@NamedTuple{…}, st::@NamedTuple{…})
    @ Lux ~/.julia/dev/Lux/src/layers/containers.jl:482
  [4] (::Chain{…})(x::SymbolicUtils.BasicSymbolic{…}, ps::@NamedTuple{…}, st::@NamedTuple{…})
    @ Lux ~/.julia/dev/Lux/src/layers/containers.jl:480
  [5] apply(model::Chain{…}, x::SymbolicUtils.BasicSymbolic{…}, ps::@NamedTuple{…}, st::@NamedTuple{…})
    @ LuxCore ~/.julia/dev/LuxCore/src/LuxCore.jl:155
  [6] outputsize(layer::Chain{@NamedTuple{…}, Nothing}, x::SymbolicUtils.BasicSymbolic{Vector{…}}, rng::TaskLocalRNG)
    @ Lux ~/.julia/dev/Lux/src/helpers/size_propagator.jl:206
  [7] macro expansion
    @ ~/.julia/dev/Symbolics/src/register.jl:116 [inlined]
  [8] var"LuxCore.stateless_apply_10505095415082029269"(nothing::Nothing, model::Chain{…}, x::SymbolicUtils.BasicSymbolic{…}, ps::ComponentVector{…})
    @ SymbolicsLuxCoreExt ~/.julia/dev/Symbolics/src/wrapper-types.jl:143
  [9] stateless_apply(model::Chain{…}, x::Symbolics.Arr{…}, ps::ComponentVector{…})
    @ SymbolicsLuxCoreExt ~/.julia/dev/Symbolics/src/wrapper-types.jl:152
 [10] top-level scope
    @ REPL[25]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

The issue is
```julia-repl
julia> Lux.NilSizePropagation.recursively_nillify(input.u)
2-element Lux.NilSizePropagation.NilArray{1}

julia> Lux.NilSizePropagation.recursively_nillify(Symbolics.unwrap(input.u))
input₊u(t)
```

I think we can change the extension to be on Lux instead of LuxCore and add a `recursively_nillify(x::SymbolicUtils.BasicSymbolic{<:Vector{<:Real}})` that re-wraps. I'm testing this locally and it seems to work.

**Comment by SebastianM-C** [comment]
I think https://github.com/JuliaSymbolics/Symbolics.jl/pull/1266 should solve this.

**Comment by SebastianM-C** [comment]
For downgrade CI, we need to bump Symbolics to the latest and we'll also need MTKStdLib version that accepts that.

**Comment by SebastianM-C** [comment]
@ChrisRackauckas should we merge this to avoid a broken version being out in the wild for too long or should we do it after downgrade works again?

**Pull request merged**
